name: CI

on: [push]

jobs:
  macOS:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
          java-version: '1.8'
    - name: download
      run: |
        export PREFIX=/tmp/artifact/dependency-clang-Darwin-x86_64/package
        rm -rf $PREFIX
        make download-src > /dev/null
    - name: build
      run: |
        export PREFIX=/tmp/artifact/dependency-clang-Darwin-x86_64/package
        export MAKEFLAGS=-j$((`sysctl -n hw.ncpu`+2))
        make build-apache-hawq-dep > /dev/null
        make build-hawq-dep > /dev/null
    - name: package
      run: |
        cd /tmp/artifact
        tar cJf dependency-clang-Darwin-x86_64.tar.xz dependency-clang-Darwin-x86_64
        rm -rf dependency-clang-Darwin-x86_64
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: /tmp/artifact

  Linux-Clang:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
          java-version: '1.8'
    - name: download
      run: |
        sudo apt-get install -y libncurses5-dev
        rm -rf /tmp/package
        make PREFIX=/tmp/package download-src> /dev/null
        mkdir -p /opt/dependency-clang-x86_64-Linux/package/
        touch /opt/dependency-clang-x86_64-Linux/package/env.sh
        source toolchain-clang-x86_64-Linux.sh
    - name: build
      run: |
        export PREFIX=/tmp/package
        export MAKEFLAGS=-j$((`nproc`+2))
        source toolchain-clang-x86_64-Linux.sh
        make build-apache-hawq-dep > /dev/null
        make build-hawq-dep > /dev/null
    - name: build-lldb
      run: |
        export PREFIX=/tmp/package
        export MAKEFLAGS=-j$((`nproc`+2))
        source toolchain-clang-x86_64-Linux.sh
        make build-lldb > /dev/null

  Linux-GCC:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
          java-version: '1.8'
    - name: download
      run: |
        sudo apt-get install -y libncurses5-dev
        rm -rf /tmp/package
        make PREFIX=/tmp/package download-src > /dev/null
    - name: build
      run: |
        export PREFIX=/tmp/package
        export MAKEFLAGS=-j$((`nproc`+2))
        export CC=gcc
        export CXX=g++
        make build-apache-hawq-dep > /dev/null
        # make build-libyarn
        # make build-hawq-dep > /dev/null
